### ISSUE TITLE
该工具前天正常下载了，这两天都弹窗“今天下载次数已达上限，已下载2次"而不能下载

### ISSUE THREAD

**Issue by liuhanyou88** [KmBase/ScienceReading#1]
谢谢Kmbase新发布的科学文库阅读改版后的好下载工具！问题如题，只在前天安装后试下载了2本，这两天想下载都弹窗，卸载重装后也仍然弹窗提示，不能再下载，请问如何解决？

**Comment by KmBase** [comment]
已经修复，打开工具更新即可
